version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "webapp/app.py", "--server.address", "0.0.0.0"]
